from abc import ABCMeta, abstractmethod


class LearningModel:
    __metaclass__ = ABCMeta

    @abstractmethod
    def get_approximation(self, qubo_list: list, problem_list: list) -> list:
        """Input a list of qubo-matrices to apply the approximation generated by the model.
           Returns a list of qubo-approximations
        """
        raise NotImplementedError

    @abstractmethod
    def set_model_weights_from_pygad(self, pygad_chromosome: list):
        """Input the chromosome from the pygad pipeline and load it into the model.
        """
        raise NotImplementedError

    @abstractmethod
    def get_initial_population(self, population_size: int) -> list:
        """Returns an initial population for training purposes"""
        raise NotImplementedError

    @abstractmethod
    def save_best_model(self, pygad_chromosome: list, model_name: str):
        """Returns an initial population for training purposes"""
        raise NotImplementedError

    @abstractmethod
    def load_best_model(self, model_name: str):
        """Returns an initial population for training purposes"""
        raise NotImplementedError

